curl -is http://pe.usps.com/prices/csv/PriorityMail_CommBase.csv > PriorityMail_CommBase.csv
curl -is http://pe.usps.com/prices/csv/PriorityMail_CommPlus.csv > PriorityMail_CommPlus.csv
curl -is http://pe.usps.com/prices/csv/RegionalRateBox_CommBase.csv > RegionalRateBox_CommBase.csv
curl -is http://pe.usps.com/prices/csv/RegionalRateBox_CommPlus.csv > RegionalRateBox_CommPlus.csv
curl -is http://pe.usps.com/prices/csv/CriticalMail_CommPlus.csv > CriticalMail_CommPlus.csv
curl -is http://pe.usps.com/prices/csv/Cubic_CommPlus.csv > Cubic_CommPlus.csv
curl -is http://pe.usps.com/prices/csv/ExpressMail_Retail.csv > ExpressMail_Retail.csv
curl -is http://pe.usps.com/prices/csv/ExpressMail_CommBase.csv > ExpressMail_CommBase.csv
curl -is http://pe.usps.com/prices/csv/ExpressMail_CommPlus.csv > ExpressMail_CommPlus.csv
curl -is http://www.usps.com/prices/_csv/april172011/FCM-Retail.csv > FCM-Retail.csv
curl -is http://www.usps.com/prices/_csv/april172011/FCM-Com_Ltrs.csv > FCM-Com_Ltrs.csv
curl -is http://www.usps.com/prices/_csv/april172011/FCM-Com_Flts.csv > FCM-Com_Flts.csv
curl -is http://www.usps.com/prices/_csv/april172011/FCM-Com_Base_Parcels.csv > FCM-Com_Base_Parcels.csv
curl -is http://www.usps.com/prices/_csv/april172011/FCM-Com_Plus_Parcels.csv > FCM-Com_Plus_Parcels.csv
curl -is http://www.usps.com/prices/_csv/april172011/Parcel_Post.csv > Parcel_Post.csv
curl -is http://pe.usps.com/prices/csv/ParcelSelect_Bar_Non.csv > ParcelSelect_Bar_Non.csv
curl -is http://pe.usps.com/prices/csv/ParcelSelect_DDU.csv > ParcelSelect_DDU.csv
curl -is http://pe.usps.com/prices/csv/ParcelSelect_NDC.csv > ParcelSelect_NDC.csv
curl -is http://pe.usps.com/prices/csv/ParcelSelect_ONDC.csv > ParcelSelect_ONDC.csv
curl -is http://pe.usps.com/prices/csv/ParcelReturnService.csv > ParcelReturnService.csv
curl -is http://www.usps.com/prices/_csv/april172011/Media_Retail.csv > Media_Retail.csv
curl -is http://www.usps.com/prices/_csv/april172011/Media_Com.csv > Media_Com.csv
curl -is http://www.usps.com/prices/_csv/april172011/Library_Retail.csv > Library_Retail.csv
curl -is http://www.usps.com/prices/_csv/april172011/Library_Com.csv > Library_Com.csv
curl -is http://www.usps.com/prices/_csv/april172011/BPM-Flats.csv > BPM-Flats.csv
curl -is http://www.usps.com/prices/_csv/april172011/BPM-Parcels.csv > BPM-Parcels.csv
curl -is http://www.usps.com/prices/_csv/april172011/Std_Letters.csv > Std_Letters.csv
curl -is http://www.usps.com/prices/_csv/april172011/Std_Flats.csv > Std_Flats.csv
curl -is http://www.usps.com/prices/_csv/april172011/Std_Parcels.csv > Std_Parcels.csv
curl -is http://www.usps.com/prices/_csv/april172011/NFMs.csv > NFMs.csv
curl -is http://www.usps.com/prices/_csv/april172011/Dom-Extra-Svcs-1.csv > Dom-Extra-Svcs-1.csv
curl -is http://www.usps.com/prices/_csv/april172011/Dom-Extra-Svcs-2.csv > Dom-Extra-Svcs-2.csv
